export const UPDATE_SEARCH_TEXT = 'UPDATE_SEARCH_TEXT';

export const GET_FILTERS_REQUEST = 'GET_FILTERS_REQUEST';
export const GET_FILTERS_SUCCESS = 'GET_FILTERS_SUCCESS';
export const GET_FILTERS_FAILED = 'GET_FILTERS_FAILED';

export const HIT_SEARCH = 'HIT_SEARCH';

export const UPDATE_MIMETYPES =  'UPDATE_MIMETYPES';

export const UPDATE_DATASETYEARS = 'UPDATE_DATASETYEARS';

export const UPDATE_SELECTED_MIMETYPES =  'UPDATE_SELECTED_MIMETYPES';

export const UPDATE_SELECTED_DATASETYEARS = 'UPDATE_SELECTED_DATASETYEARS';

export const UPDATE_SELECTED_VARIETIES = 'UPDATE_SELECTED_VARIETIES';

export const UPDATE_SELECTED_FILTER_TYPE = 'UPDATE_SELECTED_FILTER_TYPE';

export const SET_FILTER_SELECTIONS = 'SET_FILTER_SELECTIONS';

export const UPDATE_SELECTED_FILTER_VALUE_SELECTIONS = 'UPDATE_SELECTED_FILTER_VALUE_SELECTIONS';