export const LOAD_INVITATION_NOTIFICATION_REQUEST = 'LOAD_INVITATION_NOTIFICATION_REQUEST';
export const LOAD_INVITATION_NOTIFICATION_SUCCESS = 'LOAD_INVITATION_NOTIFICATION_SUCCESS';
export const LOAD_INVITATION_NOTIFICATION_FAILED = 'LOAD_INVITATION_NOTIFICATION_FAILED';

export const READ_NOTIFICATION_REQUEST = 'READ_NOTIFICATION_REQUEST';
export const READ_NOTIFICATION_SUCCESS = 'READ_NOTIFICATION_SUCCESS';
export const READ_NOTIFICATION_FAILED = 'READ_NOTIFICATION_FAILED';

export const USER_ACCEPT_INVITATION_REQUEST = 'USER_ACCEPT_INVITATION_REQUEST';
export const USER_ACCEPT_INVITATION_SUCCESS = 'USER_ACCEPT_INVITATION_SUCCESS';
export const USER_ACCEPT_INVITATION_FAILED = 'USER_ACCEPT_INVITATION_FAILED';

export const USER_ACCEPT_DATASET_INVITATION = 'USER_ACCEPT_DATASET_INVITATION';
export const USER_REJECT_DATASET_INVITATION = 'USER_REJECT_DATASET_INVITATION';

export const GROUP_ACCEPT_DATASET_INVITATION = 'GROUP_ACCEPT_DATASET_INVITATION';
export const GROUP_REJECT_DATASET_INVITATION = 'GROUP_REJECT_DATASET_INVITATION';

export const USER_REJECT_INVITATION_SUCCESS = 'USER_REJECT_INVITATION_SUCCESS';

export const ADMIN_APPROVE_INVITATION_REQUEST = 'ADMIN_APPROVE_INVITATION_REQUEST';
export const ADMIN_APPROVE_INVITATION_SUCCESS = 'ADMIN_APPROVE_INVITATION_SUCCESS';
export const ADMIN_APPROVE_INVITATION_FAILED = 'ADMIN_APPROVE_INVITATION_FAILED';

export const ADMIN_DECLINE_INVITATION_SUCCESS = 'ADMIN_DECLINE_INVITATION_SUCCESS';

export const ADMIN_ACCEPT_JOIN_REQUEST = 'ADMIN_ACCEPT_JOIN_REQUEST';
export const ADMIN_ACCEPT_JOIN_REQUEST_SUCCESS = 'ADMIN_ACCEPT_JOIN_REQUEST_SUCCESS';
export const ADMIN_ACCEPT_JOIN_REQUEST_FAILED = 'ADMIN_ACCEPT_JOIN_REQUEST_FAILED';

export const ADMIN_REJECT_JOIN_REQUEST_SUCCESS = 'ADMIN_REJECT_JOIN_REQUEST_SUCCESS';

export const APPEND_NOTIFICATION = 'APPEND_NOTIFICATION';